#!/usr/bin/env bash

set -eu

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

out="./archlive"

rm -rf "$out"
mkdir -p "$out/build"
cp -r /usr/share/archiso/configs/releng/* "$out/"
cp -r "$here"/config/* "$out/"

pushd "$out"
    ./build.sh -v
popd

echo "Generated ISO is here:"
find "$out/out" -type f
